
\ Forth tokens compiler

\ Numbers

[UNDEFINED] LIT,    [IF]  : LIT,    POSTPONE LITERAL  ;   [THEN]
[UNDEFINED] 2LIT,   [IF]  : 2LIT,   POSTPONE 2LITERAL ;   [THEN]
[UNDEFINED] SLIT,   [IF]  : SLIT,   POSTPONE SLITERAL ;   [THEN]

[DEFINED] FLITERAL  [IF]
[UNDEFINED] FLIT,   [IF] : FLIT,    POSTPONE FLITERAL ;   [THEN]
[THEN]
